Clarified capabilities
mattermost/mattermost-plugin-profanity-filter pull request #19
Opened 2020-09-16 13:36 UTC by aaronrothschild

- added marketplace installation instructions
- Added more descriptive text
- Clarified usage section

2020-09-16 13:37 UTC, aaronrothschild commented
@hanzei and @justinegeffen - I've updated the docs for the profanity filter.

2020-09-16 13:48 UTC, nathanaelhoun commented on README.md
> +2. Search for "Jira" or manually find the plugin from the list and click Install
```suggestion
2. Search for "Profanity Filter" or manually find the plugin from the list and click Install
```

2020-09-16 14:15 UTC, justinegeffen commented on README.md
> +This plugin allows you to censor profanity on your Mattermost server.  The plugin will check all messages before they are posted to any channel for matches against the "Bad Words List" that is config
```suggestion
This plugin allows you to censor profanity on your Mattermost server. The plugin will check all messages before they are posted to any channel for matches against the configured "Bad Words List". Any word matches that a user tries to submit as a message, will be replaced with a series of "*"s to replace the characters of that word.   
```

2020-09-16 14:16 UTC, justinegeffen commented on README.md
> +1. Go to Main Menu > Plugin Marketplace in Mattermost
```suggestion
1. Go to **Main Menu > Plugin Marketplace** in Mattermost.
```

2020-09-16 14:16 UTC, justinegeffen commented on README.md
> +2. Search for "Jira" or manually find the plugin from the list and click Install
```suggestion
2. Search for "Jira" or manually find the plugin from the list and click **Install**.
```

2020-09-16 14:16 UTC, justinegeffen commented on README.md
> +3. After the plugin has downloaded and been installed, click the Configure button
```suggestion
3. Once the plugin has downloaded and been installed, click **Configure**.
```

2020-09-16 18:36 UTC, hanzei requested changes
Thanks for the docs update! One small request

2020-09-16 18:36 UTC, hanzei commented on README.md
> +2. Search for "Profanity Filter" or manually find the plugin from the list and click Install
```suggestion
2. Search for "Profanity Filter" or manually find the plugin from the list and click **Install**
```

2020-09-16 18:37 UTC, aaronrothschild commented
@hanzei Looks good, thanks!

2020-09-16 18:37 UTC, hanzei approved these changes

2020-09-22 06:27 UTC, justinegeffen commented on README.md
> +This plugin allows you to censor profanity on your Mattermost server. The plugin will check all messages before they are posted to any channel for matches against the configured "Bad Words List". Any
```suggestion
This plugin allows you to censor profanity on your Mattermost server. The plugin checks all messages for matches against the configured "Bad Words List" before they are posted to any channel. The characters in any word matches are replaced with a series of "*"s.
```

2020-09-22 06:27 UTC, justinegeffen commented on README.md
> +2. Search for "Profanity Filter" or manually find the plugin from the list and click **Install**
```suggestion
2. Search for "Profanity Filter" or find the plugin in the list and click **Install**.
```

2020-09-22 06:30 UTC, justinegeffen commented on README.md
>  To configure what words are censored on your server, edit the bad words list in **System Console > Plugins > Profanity Filter > Bad words list**.
```suggestion
You can edit the bad words list in **System Console > Plugins > Profanity Filter > Bad Words list**.
```

2020-09-22 06:31 UTC, justinegeffen commented
Non-blocker: @aaronrothschild, could you confirm whether it's "Bad Words List" or "Bad words list"? I can't verify in my test instance. Thank you!

Otherwise LGTM!

2020-09-22 06:31 UTC, justinegeffen approved these changes

2020-09-25 16:02 UTC, merged